# Generated by Django 3.2.5 on 2021-07-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('info', models.CharField(help_text='一句话介绍自己，不要超过250字', max_length=255, verbose_name='个人简介')),
                ('no', models.CharField(max_length=4, verbose_name='注册编号')),
                ('number', models.CharField(max_length=6, verbose_name='用户编号')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='admin',
            name='no',
            field=models.CharField(max_length=3, verbose_name='注册编号'),
        ),
        migrations.AddConstraint(
            model_name='generaluser',
            constraint=models.UniqueConstraint(fields=('no', 'number'), name='generaluser_id'),
        ),
    ]
