# Generated by Django 3.2.6 on 2021-11-03 14:47

from django.db import migrations, models
import django.db.models.deletion
import officemanagement.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defaultAPP', '0002_auto_20210718_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='会议室名称')),
                ('introduction', models.CharField(max_length=250, verbose_name='介绍')),
                ('credit', models.IntegerField(verbose_name='楼号（几号楼）')),
                ('max_number', models.IntegerField(verbose_name='会议室最大人数')),
                ('year', models.IntegerField(default=officemanagement.models.current_year, verbose_name='年份')),
                ('semester', models.CharField(choices=[('Autumn', '上'), ('Spring', '下')], max_length=20, verbose_name='学期')),
                ('status', models.IntegerField(default=1, verbose_name='会议室状态')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultAPP.admin', verbose_name='会议室使用者')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], verbose_name='日期')),
                ('start_time', models.TimeField(verbose_name='使用开始时间')),
                ('end_time', models.TimeField(verbose_name='使用结束时间')),
                ('location', models.CharField(max_length=100, verbose_name='会议室使用地点')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('start_week', models.IntegerField(verbose_name='第几周开始')),
                ('end_week', models.IntegerField(verbose_name='第几周结束')),
                ('week_interval', models.IntegerField(choices=[(1, '无间隔'), (2, '每隔一周用一次')], default=1, verbose_name='周间隔')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officemanagement.office', verbose_name='会议室名称')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralUserOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('with_draw', models.BooleanField(default=False)),
                ('with_draw_time', models.DateTimeField(default=None, null=True)),
                ('scores', models.IntegerField(null=True, verbose_name='得分')),
                ('comments', models.CharField(max_length=250, null=True, verbose_name='会议室评价')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='5分为最满意，最低分是1分', null=True, verbose_name='用户评分')),
                ('assessment', models.CharField(max_length=250, null=True, verbose_name='用户评价')),
                ('generaluser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='defaultAPP.generaluser')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officemanagement.office')),
            ],
        ),
    ]
